# Generated by Django 3.0.6 on 2020-05-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=200)),
                ('artist_realname', models.CharField(blank=True, max_length=200)),
                ('artist_image', models.CharField(blank=True, max_length=200)),
                ('artist_profile', models.TextField(blank=True)),
                ('artist_site', models.URLField(blank=True)),
            ],
        ),
    ]
