# Generated by Django 3.0.6 on 2020-05-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=50)),
                ('recordingname', models.CharField(max_length=50)),
                ('released', models.CharField(max_length=50)),
                ('rformat', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=50)),
            ],
        ),
    ]
