# Generated by Django 3.0.6 on 2020-05-26 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0003_country_genre_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_name', models.CharField(max_length=100)),
                ('recording_image', models.CharField(blank=True, max_length=200)),
                ('release_date', models.DateField()),
                ('recording_format', models.CharField(choices=[('VL', 'Vinyl'), ('CD', 'CD'), ('DL', 'Digital'), ('CS', 'Cassette')], default='VL', max_length=2)),
                ('barcode', models.CharField(max_length=50)),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='music.Artist')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='music.Country')),
                ('genre_id', models.ManyToManyField(related_name='recording', to='music.Genre')),
                ('label_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='music.Label')),
                ('style_id', models.ManyToManyField(related_name='recording', to='music.Style')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=100)),
                ('video_url', models.URLField(blank=True)),
                ('recording_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='music.Recording')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.CharField(max_length=5)),
                ('track_title', models.CharField(max_length=200)),
                ('track_duration', models.CharField(max_length=10)),
                ('track_key', models.CharField(blank=True, max_length=50)),
                ('camelot_key', models.CharField(blank=True, max_length=50)),
                ('recording_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track', to='music.Recording')),
            ],
        ),
        migrations.CreateModel(
            name='Crate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('crate_name', models.CharField(blank=True, max_length=100)),
                ('recording_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crate', to='music.Recording')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
