# Generated by Django 3.0.6 on 2020-05-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_crate_recording_track_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='track_number',
            new_name='track_id',
        ),
    ]
