# Generated by Django 3.0.6 on 2020-05-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20200528_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crate',
            name='recording_id',
        ),
        migrations.AddField(
            model_name='crate',
            name='recording_id',
            field=models.ManyToManyField(related_name='crate', to='music.Recording'),
        ),
    ]
